完成#103任务
TaibiaoGuo/blockchainTutorial pull request #109
Opened 2021-03-19 03:30 UTC by wujun369

2021-03-19 05:48 UTC, YANYUE1 commented on book/08TechnologyTrends/08625103.md
> +
```suggestion
&emsp;&emsp;随着中国经济进入新的发展常态，开始进入转型的关键时期，从而推动了共享经济的快速崛起。

```
这句话语序不通

2021-03-19 05:51 UTC, YANYUE1 requested changes
请修改

2021-03-19 13:13 UTC, YANYUE1 approved these changes

2021-03-21 08:31 UTC, o0Roy approved these changes

2021-03-21 08:31 UTC, merged