完成#105任务
TaibiaoGuo/blockchainTutorial pull request #111
Opened 2021-03-19 12:42 UTC by wujun369

2021-03-19 13:11 UTC, YANYUE1 commented on book/08TechnologyTrends/08627105.md
> +&emsp;&emsp;每个参与者在图片共享区块链的网络上操作一个节点。患者通过发布区块链事务来访问所选择的实体。影像数据直接从来源转移到这些授权接收方，不需要通过中介机构[@patel2019framework]。
```suggestion
&emsp;&emsp;每个参与者在图片共享区块链的网络上操作一个节点，患者通过发布区块链事务来访问所选择的实体，影像数据直接从来源转移到这些授权接收方，不需要通过中介机构[@patel2019framework]。
```

2021-03-19 13:11 UTC, YANYUE1 requested changes
1、案例描述，建议用数字清单表示

2021-03-21 07:24 UTC, YANYUE1 approved these changes

2021-03-21 08:21 UTC, o0Roy approved these changes

2021-03-21 08:21 UTC, merged