完成#152任务
TaibiaoGuo/blockchainTutorial pull request #163
Opened 2021-03-25 07:03 UTC by wujun369

2021-03-25 08:48 UTC, o0Roy submitted a review, later dismissed

2021-03-25 14:12 UTC, YANYUE1 commented on book/08TechnologyTrends/0842152.md
> +*   恶意合约：区块链及智能合约的去中心化、匿名性同样可能助长恶意合约的产生。违法者可通过发布恶意的智能合约对区块链系统和用户发起攻击，也可利用合约实现匿名的犯罪交易，导致机密信息的泄露、密钥窃取或各种真实世界的犯罪行为[@欧阳丽炜2019智能合约]。
```suggestion
1. 漏洞合约：设计一个安全的智能合约的难点在于所有网络参与者都可能出于自身利益攻击或欺骗智能合约，设计者必须预见一切可能的恶意行为并设置应对措施，而传统的程序开发人员很难具备如此完美的编程能力和缜密的经济思维；
2. 恶意合约：区块链及智能合约的去中心化、匿名性同样可能助长恶意合约的产生。违法者可通过发布恶意的智能合约对区块链系统和用户发起攻击，也可利用合约实现匿名的犯罪交易，导致机密信息的泄露、密钥窃取或各种真实世界的犯罪行为[@欧阳丽炜2019智能合约]。
```

2021-03-25 14:13 UTC, YANYUE1 commented on book/08TechnologyTrends/0842152.md
> +&emsp;&emsp;VerX是一个针对合约安全性功能属性的形式化验证工作，其结合符号执行技术，提出了一种延迟谓词抽象技术。延迟谓词抽象技术将交易执行期间的符号执行信息与交易之间的抽象信息相结合，以对智能合约的时间安全属性进行自动化验证。其基本的出发点是所有的智能合约程序必须满足与其自定义的安全属性，从而将智能合约在时间上的无限状态证明转换为可达性证明。此外，为了实现更加精确的程序分析，Ver
```suggestion
&emsp;&emsp;VerX是一个针对合约安全性功能属性的形式化验证工作，其结合符号执行技术，提出了一种延迟谓词抽象技术。延迟谓词抽象技术将交易执行期间的符号执行信息与交易之间的抽象信息相结合，以对智能合约的时间安全属性进行自动化验证。其基本的出发点是所有的智能合约程序必须满足与其自定义的安全属性，从而将智能合约在时间上的无限状态证明转换为可达性证明。此外，为了实现更加精确的程序分析，VerX设计了一个全新的面向Solidity语言的符号执行引擎。VerX还意识到，所有的智能合约一定需要满足其开发者规定的自定义安全属性，因此也为用户设计了方便地规则定义入口，以便对合约的自定义安全属性进行证明[@倪远东2020智能合约安全漏洞研究综述]。
```

2021-03-25 14:16 UTC, YANYUE1 requested changes
格式错误

2021-03-27 12:26 UTC, YANYUE1 commented on book/08TechnologyTrends/0842152.md
> +&emsp;&emsp;VerX是一个针对合约安全性功能属性的形式化验证工作，其结合符号执行技术，提出了一种延迟谓词抽象技术。延迟谓词抽象技术将交易执行期间的符号执行信息与交易之间的抽象信息相结合，以对智能合约的时间安全属性进行自动化验证。其基本的出发点是所有的智能合约程序必须满足与其自定义的安全属性，从而将智能合约在时间上的无限状态证明转换为可达性证明。此外，为了实现更加精确的程序分析，Ver
verx 是什么的缩写吗？

2021-03-27 12:27 UTC, YANYUE1 requested changes
参考意见

2021-03-28 01:39 UTC, YANYUE1 approved these changes

2021-03-28 03:10 UTC, o0Roy approved these changes

2021-03-28 03:10 UTC, merged