完成#120任务
TaibiaoGuo/blockchainTutorial pull request #164
Opened 2021-03-25 08:43 UTC by o0Roy

2021-03-25 14:17 UTC, YANYUE1 commented on book/08TechnologyTrends/08131120.md
> +* EUTXO-2：在EUTXO-1的基础上，添加多种频率特性，允许用户定义自定义货币和不可替代的令牌。EUTXO-2模型允许无限制数量的货币，每个自定义货币都有一个唯一的标识符。不可替代的令牌(NFT)是一个唯一的对象，可以传输到其他用户，但不能复制。NFT在许多区块链应用程序中已被证明很有用，可以表示游戏中某个对象的所有权。
```suggestion
* EUTXO-1：在UTXO的基础上，扩展具有增强的脚本功能的基本UTXO模型，允许实现复杂的智能契约。每个事务都具有一个有效间隔，仅在当前插槽号位于事务的有效期内时，才能处理事务。Validator脚本使用有关挂起事务的信息（即假定验证成功，即将发生的事务）。 这些信息包含在称为上下文的结构中，在可能出现歧义的情况下，我们可以将此信息称为验证上下文。

* EUTXO-2：在EUTXO-1的基础上，添加多种频率特性，允许用户定义自定义货币和不可替代的令牌。EUTXO-2模型允许无限制数量的货币，每个自定义货币都有一个唯一的标识符。不可替代的令牌(NFT)是一个唯一的对象，可以传输到其他用户，但不能复制。NFT在许多区块链应用程序中已被证明很有用，可以表示游戏中某个对象的所有权。
```

2021-03-25 14:18 UTC, YANYUE1 requested changes
标题格式错误

2021-03-27 12:23 UTC, YANYUE1 approved these changes

2021-03-27 13:02 UTC, wujun369 approved these changes

2021-03-27 13:02 UTC, merged