完成#154任务
TaibiaoGuo/blockchainTutorial pull request #170
Opened 2021-03-27 06:19 UTC by wujun369

2021-03-27 12:07 UTC, o0Roy submitted a review, later dismissed

2021-03-27 12:08 UTC, YANYUE1 commented on book/08TechnologyTrends/0843154.md
> +&emsp;&emsp;在区块链交易中，交易双方的地址是其公钥的哈希值，又被称为假名，以避免和交易实体的IP地址混淆。当前区块链全局分类账中的整个交易历史都是公开的，因此任何人都可以看到资金是如何从一个假名传输到另一个假名的，并且同一用户的不同假名可能会被攻击者通过聚类分析和时间分析的方式链接在一起，从而构建交易拓扑和用户拓扑来映射出用户的真实身份，这无疑对用户的身份隐私带来了极大的威胁，因此，
```suggestion
&emsp;&emsp;在区块链交易中，交易双方的地址是其公钥的哈希值，又被称为假名，以避免和交易实体的IP地址混淆。当前区块链全局分类账中的整个交易历史都是公开的，因此任何人都可以看到资金是如何从一个假名传输到另一个假名的，并且同一用户的不同假名可能会被攻击者通过聚类分析和时间分析的方式链接在一起，从而构建交易拓扑和用户拓扑来映射出用户的真实身份，这无疑对用户的身份隐私带来了极大的威胁，因此，针对区块链中的隐私泄露问题，已经提出了一些隐私增强技术来改善区块链隐私性，大致可以分为以下三类：基于分布式节点的隐私增强技术、基于混合中心的隐私增强技术和基于密码学的隐私增强技术。针对这三个技术提供以下案例分析。
```

2021-03-27 12:14 UTC, YANYUE1 commented on book/08TechnologyTrends/0843154.md
> +议进行任何修改，同时增加了问责机制揭露盗窃现象。
全部删除，前面已写过该小节

2021-03-27 12:15 UTC, YANYUE1 commented on book/08TechnologyTrends/0844154.md
> +一事实，但是要求验证者不能获得答案的任何信息。在该技术下延伸出一种名为防弹零知识协议，该协议是基于离散对数的更节省空间的零知识证明，拥有字节数更小、验证速度更快、协议更通用的特点；
```suggestion
1. 安全多方计算能够实现计算参与各方在原始数据保留在各自本地的情况下，完成数据的协同分析，并产生正确的结果。整个计算过程中，除了计算结果能被各方获知外，其他任何有效信息均不会泄漏；
2. 零知识证明技术是一种非常特殊的证明系统。在这一证明系统里，证明者知道关于某个问题的答案，他需要向验证者证明“他知道答案”这一事实，但是要求验证者不能获得答案的任何信息。在该技术下延伸出一种名为防弹零知识协议，该协议是基于离散对数的更节省空间的零知识证明，拥有字节数更小、验证速度更快、协议更通用的特点；
```

2021-03-27 12:17 UTC, YANYUE1 requested changes
章节重复

2021-03-27 13:26 UTC, o0Roy approved these changes

2021-03-27 13:27 UTC, o0Roy approved these changes, later dismissed

2021-03-28 02:37 UTC, YANYUE1 approved these changes

2021-03-28 03:20 UTC, YANYUE1 commented on book/08TechnologyTrends/0844154.md
> +
```suggestion
#### 8.4.4.3 同态加密在区块链数据保护的应用
```
标题行下不用换行

2021-03-28 03:23 UTC, YANYUE1 submitted a review, later dismissed

2021-03-28 03:35 UTC, YANYUE1 approved these changes

2021-03-28 03:35 UTC, o0Roy approved these changes

2021-03-28 03:35 UTC, merged