完成#38任务
TaibiaoGuo/blockchainTutorial pull request #46
Opened 2021-03-12 18:29 UTC by o0Roy

2021-03-13 06:54 UTC, YANYUE1 submitted a review, later dismissed

2021-03-13 09:20 UTC, TaibiaoGuo requested changes

2021-03-14 03:25 UTC, YANYUE1 requested changes
一些细节需要修改

2021-03-14 03:33 UTC, YANYUE1 submitted a review, later dismissed

2021-03-14 03:35 UTC, wujun369 submitted a review, later dismissed

2021-03-17 14:11 UTC, TaibiaoGuo submitted a review, later dismissed

2021-03-20 05:12 UTC, wujun369 approved these changes, later dismissed

2021-03-20 05:39 UTC, YANYUE1 submitted a review, later dismissed

2021-03-20 05:51 UTC, o0Roy reviewed
签名

2021-03-21 08:28 UTC, YANYUE1 approved these changes

2021-03-21 08:47 UTC, wujun369 approved these changes

2021-03-21 08:47 UTC, merged