完成#20任务
TaibiaoGuo/blockchainTutorial pull request #58
Opened 2021-03-13 09:34 UTC by wujun369

2021-03-13 10:57 UTC, TaibiaoGuo requested changes

2021-03-14 01:57 UTC, YANYUE1 requested changes
分点描述时，每一点用“；”结尾，最后一点用“。”结尾

2021-03-16 02:17 UTC, o0Roy submitted a review, later dismissed

2021-03-16 02:35 UTC, YANYUE1 submitted a review, later dismissed

2021-03-17 14:14 UTC, TaibiaoGuo submitted a review, later dismissed

2021-03-17 14:22 UTC, o0Roy submitted a review, later dismissed

2021-03-17 14:24 UTC, o0Roy submitted a review, later dismissed

2021-03-17 14:34 UTC, TaibiaoGuo submitted a review, later dismissed

2021-03-19 17:02 UTC, o0Roy submitted a review, later dismissed

2021-03-20 05:39 UTC, YANYUE1 submitted a review, later dismissed

2021-03-21 08:01 UTC, o0Roy approved these changes

2021-03-21 08:28 UTC, YANYUE1 approved these changes

2021-03-21 08:28 UTC, merged